apiVersion: v1
kind: Namespace
metadata:
  name: target-zone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-service
  namespace: target-zone
  labels:
    app: core-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-api-service
  template:
    metadata:
      labels:
        app: core-api-service
    spec:
      containers:
      - name: web-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: core-api-service
  namespace: target-zone
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000 # Matches the Kind config port mapping for the React Frontend simulation (for testing)
  selector:
    app: core-api-service
